### ISSUE TITLE
deploy_db error using non-Pipeline model or Pipeline with 1 stage

### ISSUE THREAD

**Issue by ZachC16** [splicemachine/pysplice#70]
When using deploy_db with a non-Pipeline model or a Pipeline model with only 1 stage, model deployment fails. When a model is stored, the code assumes that the model passed in is a Pipeline, and if a Pipeline is passed in but it only has 1 stage, it is converted to a different type of model here:

https://github.com/splicemachine/pysplice/blob/master/splicemachine/mlflow_support/utilities.py#L616-L617

This results in an error in model deployment, where it is assumed the model is a Pipeline.

To reproduce: Train a Pyspark model and log it or a Pipeline with it as the sole stage using mlflow.log_model. Then, deploy the model to a database using deploy_db.

**Comment by Ben-Epstein** [comment]
https://github.com/splicemachine/pysplice/pull/76
