### ISSUE TITLE
Dataframe with vector column causes deploy_db to fail

### ISSUE THREAD

**Issue by ZachC16** [splicemachine/pysplice#73]
If a dataframe containing a vector column is passed into the deploy_db function as the `df` argument, model deployment fails. 

To replicate: deploy a Spark model to a database using the deploy_db function and pass a dataframe containing a vector column as the `df` argument.

`/opt/conda/lib/python3.7/site-packages/splicemachine/mlflow_support/mlflow_support.py in _deploy_db(db_schema_name, db_table_name, run_id, primary_key, df, create_model_table, model_cols, classes, sklearn_args, verbose, pred_threshold, replace)
    643     schema_str = ''
    644     for i in feature_columns:
--> 645         schema_str += f'\t{i} {CONVERSIONS[schema_types[str(i)]]},'
    646 
    647     try:
KeyError: 'VectorUDT'`

**Comment by Ben-Epstein** [comment]
https://github.com/splicemachine/pysplice/pull/76
